require:
  - rubocop-rspec

# Offense count: 1
# Configuration parameters: AllowSafeAssignment.
Lint/AssignmentInCondition:
  Enabled: false

# Offense count: 2
Lint/SuppressedException:
  Enabled: false

# Offense count: 84
# Configuration parameters: AllowURI, URISchemes.
Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - spec/**/*

# Offense count: 6
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/ClassAndModuleChildren:
  Enabled: false

# Offense count: 19
Style/Documentation:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - bin/**/*
    - data/**/*
    - Gemfile.lock

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Layout/HashAlignment:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Metrics/MethodLength:
  Max: 20

Layout/SpaceAroundMethodCallOperator:
  Enabled: false

Style/ExponentialNotation:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

# rspec
RSpec/NamedSubject:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false
